export const MENU_FETCH_REQUESTED = "MENU_FETCH_REQUESTED";
export const MENU_FETCH_SUCCEEDED = "MENU_FETCH_SUCCEEDED";
export const MENU_FETCH_FAILED = "MENU_FETCH_FAILED";
export const MENU_SEARCH_REQUESTED = "MENU_SEARCH_REQUESTED";

export const TASK_START = 'TASK_START';
export const TASK_UPDATE = 'TASK_UPDATE';

export const LOG_OUT = 'LOG_OUT';

// sync stroe
export const USER = 'USER';

// api
export const GET_PROGRAM_TYPE = 'GET_PROGRAM_TYPE';
export const ASYNC_GET_PROGRAM_TYPE = 'ASYNC_GET_PROGRAM_TYPE';
export const GET_ALL_ENABLE_MODULES = 'GET_ALL_ENABLE_MODULES';
export const ASYNC_GET_ALL_ENABLE_MODULES = 'ASYNC_GET_ALL_ENABLE_MODULES';
export const GET_PROGRAM_MODULES_BY_TYPE = 'GET_PROGRAM_MODULES_BY_TYPE';
export const ASYNC_GET_PROGRAM_MODULES_BY_TYPE = 'ASYNC_GET_PROGRAM_MODULES_BY_TYPE';

export const GET_COMMON = 'GET_COMMON';
export const ASYNC_GET_COMMON = 'ASYNC_GET_COMMON';

//prcess
export const GET_ALL_ENABLE_PROCESS_MODULES = 'GET_ALL_ENABLE_PROCESS_MODULES';
export const ASYNC_GET_ALL_ENABLE_PROCESS_MODULES = 'ASYNC_GET_ALL_ENABLE_PROCESS_MODULES'

export const GET_TEST_PLAN = 'GET_TEST_PLAN';
export const ASYNC_GET_TEST_PLAN = 'ASYNC_GET_TEST_PLAN';


//program
export const GET_ALL_PROJECT = 'GET_ALL_PROJECT';

//program
export const GET_ALL_TASK = 'GET_ALL_TASK';
export const ASYNC_GET_ALL_TASK = 'ASYNC_GET_ALL_TASK';

//dictionary
export const GET_ALL_DICTIONARY = 'GET_ALL_DICTIONARY';
export const ASYNC_GET_ALL_DICTIONARY = 'ASYNC_GET_ALL_DICTIONARY';